### ISSUE TITLE
Names Don't Appear in Survival

### ISSUE THREAD

**Issue by CyberRat7** [BrokenK3yboard/UsefulSpyglass#7]
When you look at an entity or block with a spyglass in survival mod the name doesnt appear, it works fine in creative tho.
![2024-02-22_11 09 57](https://github.com/BrokenK3yboard/UsefulSpyglass/assets/131731394/02ee0e9e-6d64-4715-93c7-bde7127d73d8)
![2024-02-22_11 04 48](https://github.com/BrokenK3yboard/UsefulSpyglass/assets/131731394/6d4f1c6f-b7de-4d82-b16e-565763edf86b)

**Comment by BrokenK3yboard** [comment]
Should be fixed in version 0.5.1.

**Comment by CyberRat7** [comment]
![2024-03-06_16 12 36](https://github.com/BrokenK3yboard/UsefulSpyglass/assets/131731394/77625c07-7fac-41c5-82a8-b936b9037574)
![2024-03-06_16 12 53](https://github.com/BrokenK3yboard/UsefulSpyglass/assets/131731394/05ceed92-48e4-4251-90bc-39a4672d9d06)

Still isnt fixed for entities
